/feature/4-이메일 인증
f-lab-edu/flab-bada pull request #10
Opened 2023-06-07 10:29 UTC by LeeSungGuk

1. 이메일 인증 
2. 테스트 코드 추가

2023-06-12 07:05 UTC, f-lab-zion requested changes
👍 수고하셨습니다 코멘트 확인하셔서 수정 후 review 요청주세요

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/database/database.py
> +# import redis
필요없는 코드는 주석처리 대신 삭제가 좋습니다

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/database/database.py
> +    session = StrictRedis(host=host, port=port)
`host`, `port` 같은 정보는 config 에서 읽어오도록 하는게 관리 측면에서 좋습니다

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/domain/email/email_controller.py
> +@email_router.post("/send/email")
URL 구성을 다음과 같이 정의하셨습니다.
```
/send/email
/confirm/email 

```
하기와 같이 변경하면 무엇이 좋을까요? 어떤 점이 달라지고 어떤게 나을지 한번 검토해보세요
```
/email/send
/email/confirm 
```

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/domain/email/email_controller.py
> +async def simple_send(email: EmailSchema, email_service: EmailService = Depends()) -> JSONResponse:
```suggestion
async def simple_send(email_schema: EmailSchema, email_service: EmailService = Depends()) -> JSONResponse:
```
변수명도 그 의미를 충분히 드러나도록 설정하는게 좋습니다 `email` 이라는 단어는 서비스일까요? 레포지토리일까요? 스키마일까요? 모호한 표현은 지양해봅시다

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/domain/email/email_controller.py
> +        return JSONResponse(status_code=500, content={"message": e.__str__()})
Tip) 에러 응답을 주기 위하여 JSONResponse를 여러 군데서 사용하고 있습니다. content의 일관성을 위해서 별도의 클래스를 생성해서 관리하는 것도 방법입니다.
ex) [json rpc  - error object](https://www.jsonrpc.org/specification#error_object )

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/domain/email/email_controller.py
> +async def confirm_email(email: EmailSecret, email_service: EmailService = Depends()) -> JSONResponse:
```suggestion
async def confirm_email(email_secret: EmailSecret, email_service: EmailService = Depends()) -> JSONResponse:
```

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/domain/email/email_repository.py
> +        return data
```suggestion
        if not data:
            return ""
        return data.decode("utf-8")
```
control flow는 위와 같이 에러나 예외 처리를 먼저 해주면 코드 가독성을 높일 수 있습니다

2023-06-12 07:05 UTC, f-lab-zion commented on flab_bada/domain/email/email_service.py
> +        yag = yagmail.SMTP({"jin3137@gmail.com": "flab-bada"}, "mtveqsvobkhqzlrt")
개인정보는 코드에 노출되어서는 안됩니다. 환경변수를 통해서 숨기도록 합시다

2023-06-13 13:25 UTC, LeeSungGuk commented on flab_bada/domain/email/email_controller.py
> +@email_router.post("/send/email")
동사 표현을 쓰고 명사를 쓸려고 했는데, 
rest api 명명 규칙을 보니 명사로만 표기 ~ 명사는 리소스를 나타낸다. 
복잡한 리소스에는 연관리스소 표기하는 방식이 더 잘 이해 할수 있다고 합니다.
email -> send 이렇게 표기하는게 사용자로 하여금 더 잘 이해할수 있다고 합니다.

2023-06-14 04:38 UTC, LeeSungGuk reviewed
리뷰 완료 하였습니다.

2023-06-14 05:53 UTC, f-lab-zion approved these changes
하나만 확인하고 머지해주세요. 일단 approve 하겠습니다

2023-06-14 05:53 UTC, f-lab-zion commented on flab_bada/domain/email/email_service.py
> +            yag = yagmail.SMTP({"jin3137@gmail.com": "flab-bada"}, "mtveqsvobkhqzlrt")
비밀번호가 노출되지 않도록 변경해주세요

2023-06-14 12:02 UTC, merged