/feature/5-사용자 정보 및 강의 등록
f-lab-edu/flab-bada pull request #11
Opened 2023-07-05 07:58 UTC by LeeSungGuk

1. 이메일 인증에서 토큰 으로 변경
2. 통합 작업이 필요함 (금요일 까지 commit)
3. 사용자에서 강사로 롤 변경
4. 강의 등록 로직 추가 
5. 강의 관련 로직 개발해서 commit

2023-07-18 15:47 UTC, f-lab-zion requested changes
코멘트 달았습니다.

2023-07-18 15:47 UTC, f-lab-zion commented on flab_bada/domain/email/email_service.py
> +            url: http://localhost:8000/email/confirm?token={self.get_secret_num(email=email)}&email={email}
url 에 localhost 가 들어가는 것보다 환경변수로 서버 주소를 받고 그것을 활용하도록 하면 어떨까요?

2023-07-18 15:47 UTC, f-lab-zion commented on flab_bada/domain/email/email_service.py
> +        return check_data
```suggestion
        return token == self.get_secret_num(email)
```
동일한 의미를 갖도록 코드를 간결하게 작성하는 연습도 해보세요 
코드만 읽어도 충분히 그 의미가 해석되면 주석을 굳이 달아야할 필요가 없어집니다

2023-07-18 15:47 UTC, f-lab-zion commented on flab_bada/domain/lecture/lectures_controller.py
> +        raise HTTPException(status_code=500, detail=e.__str__())
https://blog.marzeta.pl/maximizing-reliability-in-fastapi-global-exception-handling
fastapi exception handler 를 이용해서 보다 깔끔하게 코드를 리팩토링 해볼 수 있을 것 같습니다.
한번 고민해보세요

2023-07-18 15:47 UTC, f-lab-zion commented on flab_bada/domain/lecture/lectures_repository.py
> +        pass
pass 하나요?

2023-07-18 15:47 UTC, f-lab-zion commented on flab_bada/utils/bcrypt.py
> +        expire = datetime.utcnow() + timedelta(minutes=15)
```suggestion
def create_confirm_token(data: dict, expires_delta: timedelta = timedelta(minutes=15)):
    to_encode = data.copy()
    expire = datetime.utcnow() + expires_delta
```
default 값을 활용해도 좋겠습니다.

2023-07-19 11:57 UTC, LeeSungGuk commented on flab_bada/domain/email/email_service.py
> +            url: http://localhost:8000/email/confirm?token={self.get_secret_num(email=email)}&email={email}
네 수정 하였습니다. ^^

2023-07-19 11:58 UTC, LeeSungGuk commented on flab_bada/domain/email/email_service.py
> +        return check_data
아 감사합니다. ~ 위에는 진짜 버릇 처럼 저렇게 하는 듯 합니다. 
간결하게 작성하는 방법 연습 해보겠습니다.

2023-07-19 11:58 UTC, LeeSungGuk commented on flab_bada/domain/lecture/lectures_repository.py
> +        pass
나중에 하려다가 까먹었네요 ^^ 추가하였습니다.

2023-07-19 11:59 UTC, LeeSungGuk commented on flab_bada/utils/bcrypt.py
> +        expire = datetime.utcnow() + timedelta(minutes=15)
넵 감사합니다.

2023-08-21 06:01 UTC, f-lab-zion approved these changes

2023-08-29 13:52 UTC, merged