회원가입, 로그인, 내 정보
f-lab-edu/flab-bada pull request #3
Opened 2023-04-27 13:15 UTC by LeeSungGuk

[이성국]

1. 회원가입
2. 로그인
- jwt 토큰 생성
3. 내 정보
- jwt 토큰 으로 확인

2023-05-08 10:42 UTC, f-lab-zion requested changes
- 전체적으로 테스트 케이스를 좀더 보강하면 좋겠습니다
- 비밀번호 체크 로직 등이 pydantic model 에 validator 추가로 대응하는 것도 방법입니다
- 클린아키텍처 적용하면서 dependency injection 을 적절히 활용해보세요

2023-05-08 10:42 UTC, f-lab-zion commented on .github/workflows/test-actions.yaml
> +#        run: poetry run pytest
이건 일부러 빼신건가요? 추가하는게 좋아보입니다

2023-05-08 10:42 UTC, f-lab-zion commented on flab_bada/domain/users/user_controller.py
> +        us = UserService(email=email, pw=pw)
UserService에 넘어가는 parameter를 pydantic model로 정의하여 쓸 수도 있습니다

2023-05-08 10:42 UTC, f-lab-zion commented on flab_bada/domain/users/user_controller.py
> +        print(f"email: {email}")
디버깅용 메시지는 삭제합니다

2023-05-08 10:42 UTC, f-lab-zion commented on flab_bada/domain/users/user_service.py
> +    def chk_email_password_user(self, db: Session) -> bool:
개인적으로 `chk` 같은 줄임말보다는 특별한 이유가 없다면 `check`로 풀어쓰는게 가독성 측면에서 좋아보입니다

2023-05-08 10:42 UTC, f-lab-zion commented on flab_bada/domain/users/user_service.py
> +    ACCESS_TOKEN_EXPIRE_MINUTES,
이런 값은 config 에서 일괄 관리하는게 좋아보입니다

2023-05-10 01:03 UTC, LeeSungGuk commented on .github/workflows/test-actions.yaml
> +#        run: poetry run pytest
db test에서 오류가 나서 뺐는데 ~ 이번에 github action에 mysql 테스트 추가 하였습니다.

2023-05-10 01:03 UTC, LeeSungGuk commented on flab_bada/domain/users/user_controller.py
> +        us = UserService(email=email, pw=pw)
네 수정 하였습니다. 감사합니다.

2023-05-10 01:04 UTC, LeeSungGuk commented on flab_bada/domain/users/user_controller.py
> +        print(f"email: {email}")
넵 감사합니다.

2023-05-10 01:04 UTC, LeeSungGuk commented on flab_bada/domain/users/user_service.py
> +    def chk_email_password_user(self, db: Session) -> bool:
가독성 측면에서 생각하면서 개발하도록 하겠습니다.

2023-05-10 01:05 UTC, LeeSungGuk commented on flab_bada/domain/users/user_service.py
> +    ACCESS_TOKEN_EXPIRE_MINUTES,
네 수정 완료 하였습니다.

2023-05-10 01:24 UTC, merged